name: Deploy to GitHub pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - name: Deploy to gh-pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BUILD_DIR: dist
